### ISSUE TITLE
Swift 3 compatibility

### ISSUE THREAD

**Issue by lfarah** [kovpas/PMZSwitch#2]
Hey, I'd love to see this lib available in Swift 3 so I can implement it in my project.

Thanks 😄

**Comment by LinusGeffarth** [comment]
Check the version I published on CocoaPods for Swift 4.2 support
https://github.com/LinusGeffarth/PMZSwitch

**Comment by kovpas** [comment]
@LinusGeffarth I think it would make sense to contribute back to this repo ;)

**Comment by LinusGeffarth** [comment]
Contribute as in how?
@kovpas

**Comment by kovpas** [comment]
@LinusGeffarth I meant pull request with Swift 4 support.

**Comment by LinusGeffarth** [comment]
@kovpas, will do!

**Comment by kovpas** [comment]
Thanks @LinusGeffarth for the contribution! (#4)
